### ISSUE TITLE
Provided installer

### ISSUE THREAD

**Issue by dschwartz783** [RyuKojiro/novafix#8]
I went over some of the scripts embedded in the installer, and it would seem that running it a second time would have the same effect that the Makefile originally had. It'll overwrite the original binary if run a second time. The resolution in the Makefile should work for this, but it's in a somewhat dangerous state currently.

**Comment by RyuKojiro** [comment]
Yeah, I tried to add a rule to test for the existence of the .original, but Installer.app wasn't respecting it. That's why I added the note in the instructions to just trash and reinstall the EV Nova app if it breaks it. I suppose I could have added logic to the script to check for the existence and exit with a failing return code to bail out pre-installation, but I really just threw it together. I'll probably put the pmdoc into the repo and maybe add a make target for building the pkg tonight.

**Comment by RyuKojiro** [comment]
Looking at the pmdoc, it stores entirely absolute paths, and is not hard to recreate. I'm going to leave it out of git.
